### PR TITLE
added spadina testnet

### PR DESCRIPTION
**Pull request by dpdanpittman**

### CODE REVIEW

**Comment by dpdanpittman** [comment]
Not sure why the build-windows and win-py37-script tests failed cause I didn't touch those

**Comment by hwwhww** [comment]
Hey @dpdanpittman, thanks!
Spadina setting PR (#96) has been merged into `dev` branch. `dev` branch will be merged into `master` branch soon for the next release! (today or tomorrow)

**Comment by dpdanpittman** [comment]
No problem, thank you!  I actually saw that about 2 minutes after
requesting.

**Comment by dpdanpittman** [comment]
Love it!  It's no problem at all.

**Pull request closed without merging**
