### PR TITLE
Add Gnosis Beacon Chain network

### PR DESCRIPTION
**Pull request by k1rill-fedoseev**
More info about the Gnosis Beacon Chain:
https://docs.gnosischain.com
https://beacon.gnosischain.com/

### CODE REVIEW

**Comment by CarlBeek** [comment]
Unfortunately, I'm not going to include this PR as I think it is important to maintain the "purity" of this repo. I appreciate that maintaining your own fork seems silly from your perspective, but this CLI is supposed to be minimal and serve Ethereum Beacon Chain validators. It is about the memetic implications of including other projects into this repo as opposed to the technical ones, which are pretty much trivial.

Furthermore, if we include this PR, it becomes much harder to draw a line as to which other chains (and their testnets) get to be included.

**Comment by shegenerates** [comment]
@CarlBeek, I strongly urge you to reconsider this. xdai / gnosis chain is canon & a good faith chain with positive network effects on Ethereum, and completely ideologically aligned with ETH 2. I even think it has the chance to eventually merge into one of the first shards of Ethereum way down the road.

[xdai is directly part of nethermind](https://github.com/NethermindEth/nethermind/search?q=xdai&type=commits) and other core ethereum clients, and the devs behind it have contributed to many core ethereum products. [xdai codebase is directly part of OpenEthereum client](https://github.com/openethereum/openethereum/search?q=xdai&type=code) too. And I'm sure I dont need to tell you about the positive ecosystem impact gnosis has had with its free tools like Safe.

I agree with you that it can be difficult to draw a line with what should be included / considered pure or not. To me and many other devs it is obvious that xdai is clearly on the "pure" side of that line, as demonstrated by synergies of having the xdai codebase in other (even minified) core ethereum clients. 

Thank you for reconsidering, we all really appreciate your hard work maintaining this CLI.

**Comment by youngkidwarrior** [comment]
Its not only what @shegenerates says,


Its also the countless hours xDai team has put into being the primary DAO chain. 

DAOs focused on scaling Ethereum from a community/social aspect all choose xDai. I can't stress how much that meant to me choosing Ethereum/xDai as my primary chain to build atop

**Comment by thekerp** [comment]
Here to second these things and to add that this notion of “purity” strikes me as anti-theatrical to the idea of composability, anti-fragility, and community driven growth. And the notion that this sets any sort of precedent for other chains is just a terrible slippery slope argument, it’s logically unsound. (Obnoxious point to make, but true 🤷‍♂️)

**Pull request closed without merging**
