### PR TITLE
Allow 4-character abbreviations of mnemonic words ...

### PR DESCRIPTION
**Pull request by yorickdowne**
... when using the `existing-mnemonic` workflow.

This addresses #167 

Choices made:

Because of the way the dict lookups are written, I decided to normalize to 'NFKC' and slice to 4 characters or less. The normalization is there so that combining Unicode characters work and the string doesn't get sliced to 3 visible characters.

I have no particular attachment to this way of handling it. If you'd rather not normalize and do a partial match on dict keys instead, I am game. If there's a third method you favor, ditto.

`new-mnemonic` workflow has not been touched and still does a straight compare. One might discuss whether that workflow should allow abbreviations as well, but that might be a different PR.

This code passes the test suite.

### CODE REVIEW

**Review by lukas131313 — APPROVED** [review]
R

**Comment by yorickdowne** [comment]
Please give this another look for inclusion.

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by yorickdowne** [comment]
This is now failing one specific test mnemonic. Let me see why that is.
```
test_mnemonic = 'abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco abaco agitare'
```

**Comment by yorickdowne** [comment]
I know why this fails, the logic to create a word language map is wrong. I'm glad this got caught before it made it in! Let me think on how to improve

**Comment by yorickdowne** [comment]
This now passes all tests. Logic has been changed. Previously I normalized and sliced to 4 characters while constructing `word_language_map`. The way Python works, this turned out to be a very bad idea: There are multiple overlaps in abbreviations, and the map ended up with only one word to language mapping, not several.

Instead, I am now using a nested for list comprehension, then flatten the resulting 2D list again. If there's a more elegant way of doing this, please share!

Because abbreviations can match several languages, and then merely fail the checksum, I am now continuing the search through the languages when a checksum fails, rather than returning `None` on the first failure.

**Comment by yorickdowne** [comment]
Please give this another look for inclusion.

Also, please give feedback on whether changing the two `pass` statements to `continue` would be welcome.

**Comment by yorickdowne** [comment]
Please give this another look for inclusion. If there are concerns, please raise them.

**Comment by yorickdowne** [comment]
Ping to get this considered for inclusion, please.

**Pull request closed without merging**
