### PR TITLE
Remove Pyrmont testnet

### PR DESCRIPTION
**Pull request by Zachinquarantine**
This PR removes the deprecated pyrmont testnet once it's fully shut down

### CODE REVIEW

**Comment by hwwhww** [comment]
@Zachinquarantine 
Thanks! This PR makes sense to me.
Sorry I might click the "Ready to review" button too early and yeah we may have to wait for a few more days.

**Comment by lodotek** [comment]
I'm curious why this is still a Draft PR 🤔

**Review by lodotek — APPROVED** [review]
LGTM 👍

**Comment by CarlBeek** [comment]
thanks @Zachinquarantine! I totally forgot about this PR :(. I ended up duplicating it in @240.

**Pull request closed without merging**
